name: Integracion y entrega continua
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@master
      name: copiar repositorio con scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "*"
        target: "/usr/local/apache2/htdocs"